export const GAME_MODE_PICK_TEAM = 'pick team'
export const GAME_MODE_GAME = 'game'
export const ASSASSIN = 'assassin'
export const BYSTANDER = 'bystander'
export const TEAM_1 = '1'
export const TEAM_2 = '2'
export const SPYMASTER = 'spymaster'
